version: '3'

services:
  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: newtonlo
      POSTGRES_PASSWORD: newtonlo
      POSTGRES_DB: c26_frd010
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  c26-nest-server:
    image: "nl2651990/c26-nest-server:latest"
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
